

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: infracost/cloud-pricing-api:latest # Latest stable release
    ports: 
        - 4000:4000
    environment:
      - INFRACOST_API_KEY=${INFRACOST_API_KEY}
      - SELF_HOSTED_INFRACOST_API_KEY=${SELF_HOSTED_INFRACOST_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=cloud_pricing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on: [postgres]
    # networks:
    #   - cloud_pricing_api

  shell:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
        - 4000:4000
    environment:
      - INFRACOST_API_KEY=${INFRACOST_API_KEY}
      - SELF_HOSTED_INFRACOST_API_KEY=${SELF_HOSTED_INFRACOST_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=cloud_pricing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumes:
      - ./:/usr/src/ap2
    # networks:
    #   - cloud_pricing_api
    networks:
      - no-internet

  init_job:
    build:
      context: .
      dockerfile: Dockerfile
    image: infracost/cloud-pricing-api:latest # Latest stable release
    environment:
      - INFRACOST_API_KEY=${INFRACOST_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=cloud_pricing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on: [postgres]
    # networks:
    #   - cloud_pricing_api
    command: ["npm", "run", "job:init"]

  # Cron: Add a cron job to run every week to update the database data. The cron entry should look something like:
  # 0 4 * * SUN docker-compose run --rm update_job npm run job:update >> /var/log/cron.log 2>&1
  update_job:
    build:
      context: .
      dockerfile: Dockerfile
    image: infracost/cloud-pricing-api:latest # Latest stable release
    environment:
      - INFRACOST_API_KEY=${INFRACOST_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=cloud_pricing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on: [postgres]
    # networks:
    #   - cloud_pricing_api
    command: ["npm", "run", "job:update"]

  postgres:
    image: postgres:14.4
    user: postgres
    environment:
      - POSTGRES_DB=cloud_pricing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - no-internet
    # networks:
    #   - cloud_pricing_api

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "35480:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.co
      PGADMIN_DEFAULT_PASSWORD: a
      PGADMIN_DISABLE_POSTFIX: True
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    networks:
      - no-internet
      - gtw
 
volumes:
  postgres-data:

# networks:
#   cloud_pricing_api:


networks: 
  default: 
      name: gtw
  gtw:
    name: gtw
  no-internet:
    driver: bridge
    internal: true